--- 
title: "California Independent System Operator Hourly Demand"
subtitle: "LinkedIn Learning"
format: dashboard
--- 

```{r}
library(dplyr)
library(plotly)
library(lubridate)

```

```{r}
data_path <- "../csv/ciso_grid_R.csv"
data <- readr::read_csv(file = data_path, col_types = readr::cols(
    period = readr::col_datetime(format = ""),
    subba = readr::col_character(),
    subba_name = readr::col_character(),
    parent = readr::col_character(),
    parent_name = readr::col_character(),
    value = readr::col_double(),
    value_units = readr::col_character()
))

# Calculate the date range for the most recent month
max_date <- max(data$period, na.rm = TRUE)
min_date <- max_date %m-% months(1)

```





## row

```{r}
#| title: Hourly Demand By Provider


p <- plot_ly(
    data = data,
    x = ~period,
    y = ~value,
    color = ~subba,
    type = 'scatter',
    mode = 'lines'
) %>% layout(
    xaxis = list(
        title = "Date",
        range = c(min_date, max_date)
    ),
    yaxis = list(title = "Hourly Demand")
)

p
```
